version: '3.5'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
volumes:
  my-db:
